#!/usr/bin/env python3
"""Apply repeatable SEO / AI-search metadata to Freedom Lab static pages.

This script keeps canonical URLs, og:url, baseline JSON-LD, and sitemap.xml
in sync for future hand-written static pages. It intentionally avoids private,
noindex, app-shell, and Google verification pages.
"""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from html import escape, unescape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE = "https://freedomlab.nyc"
DEFAULT_IMAGE = f"{SITE}/static/img/FL%20Signature%20Rectangular2.png"
GA_SNIPPET_MARKER = "googletagmanager.com/gtag/js?id=G-5L8YH7QGBD"

EXCLUDE_PARTS = {
    ".git", ".hermes", "internal", "ghostr", "dashboard", "peddler", "poll", "links",
    "sketches", "templates",
}
EXCLUDE_FILES = {"google962eebcd38de853f.html"}
NO_SITEMAP_PATHS = {
    "/404.html", "/print-page.html", "/print-page/", "/tag-tree-options.html", "/skill/",
    "/join/digital/", "/join/waitlist/", "/join-hackerspace/", "/thankyou/", "/onion/"
}
HIGH_PRIORITY = {"/": "1.0", "/classes-events/": "0.9", "/resources/": "0.9", "/join/": "0.8"}

ORG_SCHEMA = {
    "@context": "https://schema.org",
    "@type": ["Organization", "LocalBusiness"],
    "@id": f"{SITE}/#organization",
    "name": "Freedom Lab NYC",
    "url": f"{SITE}/",
    "logo": f"{SITE}/static/img/FL%20Signature%20Rectangular2.png",
    "image": DEFAULT_IMAGE,
    "description": "Freedom Lab NYC is a New York City community for hands-on freedom tech education, including Bitcoin, open-source AI, privacy tools, encrypted messaging, self-hosting, Nostr, Tor, and decentralized networks.",
    "areaServed": {"@type": "City", "name": "New York"},
    "address": {"@type": "PostalAddress", "addressLocality": "New York", "addressRegion": "NY", "addressCountry": "US"},
    "sameAs": [
        "https://x.com/FreedomLabNYC",
        "https://www.linkedin.com/company/freedom-lab-nyc/",
        "https://github.com/FreedomLabNYC",
    ],
}


def rel_url(path: Path) -> str:
    rel = path.relative_to(ROOT).as_posix()
    if rel == "index.html":
        return "/"
    if rel.endswith("/index.html"):
        return "/" + rel[: -len("/index.html")] + "/"
    return "/" + rel


def is_excluded(path: Path) -> bool:
    rel = path.relative_to(ROOT)
    if path.name in EXCLUDE_FILES:
        return True
    if any(part in EXCLUDE_PARTS for part in rel.parts):
        return True
    return False


def is_noindex(html: str, url_path: str) -> bool:
    return bool(re.search(r'<meta[^>]+name=["\']robots["\'][^>]+noindex', html, re.I)) or url_path in NO_SITEMAP_PATHS


def get_tag(html: str, pattern: str) -> str:
    m = re.search(pattern, html, re.I | re.S)
    return unescape(m.group(1).strip()) if m else ""


def page_title(html: str) -> str:
    title = get_tag(html, r"<title[^>]*>(.*?)</title>")
    if title:
        return re.sub(r"\s+", " ", title)
    h1 = get_tag(html, r"<h1[^>]*>(.*?)</h1>")
    return re.sub(r"<[^>]+>", "", h1) or "Freedom Lab NYC"


def page_description(html: str) -> str:
    desc = get_tag(html, r'<meta[^>]+name=["\']description["\'][^>]+content=["\']([^"\']*)["\']')
    if desc:
        return desc
    p = get_tag(html, r"<p[^>]*>(.*?)</p>")
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", p))[:300]


def resource_tags(html: str) -> list[str]:
    return [unescape(x.strip()) for x in re.findall(r'<span class="tutorial-tag">(.*?)</span>', html, re.I | re.S)]


def plain_text(html_fragment: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", html_fragment)).strip()


def resource_metadata(html: str) -> dict[str, str]:
    data = {}
    text = plain_text(html)
    patterns = {
        "audience": r"Audience:\s*([^\n\.]{3,120})",
        "timeRequired": r"(?:Duration|Time required):\s*([^\n\.]{2,80})",
        "prerequisites": r"Prerequisites?:\s*([^\n]{3,180})",
    }
    for key, pat in patterns.items():
        m = re.search(pat, text, re.I)
        if m:
            data[key] = m.group(1).strip(" .")
    outcomes = re.search(r"Outcomes?:\s*(.*?)(?:Agenda|Steps|Materials|Prerequisites|</section>|$)", html, re.I | re.S)
    if outcomes:
        items = [plain_text(x) for x in re.findall(r"<li[^>]*>(.*?)</li>", outcomes.group(1), re.I | re.S)[:6]]
        if items:
            data["learningResourceType"] = "hands-on tutorial"
            data["teaches"] = items
    return data


def json_script(schema: object) -> str:
    return '<script type="application/ld+json">\n' + json.dumps(schema, ensure_ascii=False, indent=2) + '\n</script>'


def remove_generated_seo(head: str) -> str:
    head = re.sub(r"\n?\s*<!-- Canonical / SEO -->\s*\n\s*<link rel=\"canonical\"[^>]*>\s*\n?", "\n", head, flags=re.I)
    marker = '<!-- Freedom Lab structured data (generated by scripts/apply-seo.py) -->'
    start = head.find(marker)
    if start != -1:
        next_google = head.find('<!-- Google tag', start)
        if next_google != -1:
            head = head[:start] + head[next_google:]
        else:
            head = head[:start]
    return head


def upsert_og_url(head: str, canonical: str) -> str:
    tag = f'<meta property="og:url" content="{canonical}">'
    if re.search(r'<meta[^>]+property=["\']og:url["\'][^>]*>', head, re.I):
        return re.sub(r'<meta[^>]+property=["\']og:url["\'][^>]*>', tag, head, count=1, flags=re.I)
    m = re.search(r'<meta property="og:type"[^>]*>', head, re.I)
    if m:
        insert_at = m.end()
        return head[:insert_at] + "\n    " + tag + head[insert_at:]
    return head


def schemas_for(path: Path, html: str, canonical: str) -> list[object]:
    url_path = rel_url(path)
    title = page_title(html)
    desc = page_description(html)
    schemas: list[object] = []
    if url_path == "/":
        schemas.append(ORG_SCHEMA)
        schemas.append({
            "@context": "https://schema.org",
            "@type": "WebSite",
            "@id": f"{SITE}/#website",
            "url": f"{SITE}/",
            "name": "Freedom Lab NYC",
            "publisher": {"@id": f"{SITE}/#organization"},
            "description": desc,
        })
    elif url_path.startswith("/events/"):
        h1 = get_tag(html, r"<h1[^>]*>(.*?)</h1>")
        clean_h1 = re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", h1)).strip() or title.replace(" | Freedom Lab NYC", "")
        schemas.append({
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "Home", "item": f"{SITE}/"},
                {"@type": "ListItem", "position": 2, "name": "Classes & Events", "item": f"{SITE}/classes-events/"},
                {"@type": "ListItem", "position": 3, "name": clean_h1, "item": canonical},
            ],
        })
    elif url_path.startswith("/resources/") and url_path != "/resources/":
        h1 = get_tag(html, r"<h1[^>]*>(.*?)</h1>")
        clean_h1 = re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", h1)).strip() or title.replace(" | Freedom Lab NYC", "")
        schema = {
            "@context": "https://schema.org",
            "@type": "TechArticle",
            "@id": canonical + "#article",
            "headline": clean_h1,
            "name": clean_h1,
            "description": desc,
            "url": canonical,
            "image": DEFAULT_IMAGE,
            "publisher": {"@id": f"{SITE}/#organization"},
            "author": {"@id": f"{SITE}/#organization"},
            "mainEntityOfPage": canonical,
        }
        tags = resource_tags(html)
        if tags:
            schema["keywords"] = ", ".join(tags)
            schema["about"] = tags
        schema.update(resource_metadata(html))
        schemas.append(schema)
        schemas.append({
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "Home", "item": f"{SITE}/"},
                {"@type": "ListItem", "position": 2, "name": "Resources", "item": f"{SITE}/resources/"},
                {"@type": "ListItem", "position": 3, "name": clean_h1, "item": canonical},
            ],
        })
    elif url_path == "/classes-events/":
        schemas.append({
            "@context": "https://schema.org",
            "@type": "CollectionPage",
            "@id": canonical + "#collection",
            "name": "Classes & Events | Freedom Lab NYC",
            "description": desc,
            "url": canonical,
            "publisher": {"@id": f"{SITE}/#organization"},
            "about": ["Bitcoin", "privacy", "open-source AI", "self-hosting", "freedom tech"],
        })
        events_path = ROOT / "classes-events" / "events.json"
        if events_path.exists():
            try:
                events = json.loads(events_path.read_text(encoding="utf-8")).get("events", [])[:24]
            except Exception:
                events = []
            event_items = []
            for i, ev in enumerate(events, 1):
                event = {
                    "@type": "Event",
                    "name": ev.get("name") or "Freedom Lab NYC event",
                    "startDate": ev.get("date"),
                    "endDate": ev.get("end"),
                    "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
                    "eventStatus": "https://schema.org/EventScheduled",
                    "url": ev.get("url") or canonical,
                    "image": ev.get("cover") or DEFAULT_IMAGE,
                    "organizer": {"@id": f"{SITE}/#organization"},
                    "location": {
                        "@type": "Place",
                        "name": ev.get("venue") or "Freedom Lab NYC",
                        "address": ev.get("location") or "New York, NY",
                    },
                }
                if ev.get("price"):
                    event["offers"] = {"@type": "Offer", "price": ev.get("price"), "url": ev.get("url") or canonical, "availability": "https://schema.org/InStock"}
                event_items.append({"@type": "ListItem", "position": i, "item": event})
            if event_items:
                schemas.append({
                    "@context": "https://schema.org",
                    "@type": "ItemList",
                    "@id": canonical + "#events",
                    "name": "Freedom Lab NYC classes and events",
                    "itemListElement": event_items,
                })
    elif url_path == "/resources/":
        schemas.append({
            "@context": "https://schema.org",
            "@type": "CollectionPage",
            "@id": canonical + "#collection",
            "name": "Freedom Lab NYC Resources",
            "description": desc,
            "url": canonical,
            "publisher": {"@id": f"{SITE}/#organization"},
        })
    else:
        schemas.append({
            "@context": "https://schema.org",
            "@type": "WebPage",
            "@id": canonical + "#webpage",
            "name": title,
            "description": desc,
            "url": canonical,
            "publisher": {"@id": f"{SITE}/#organization"},
        })
    return schemas


def process_html(path: Path) -> bool:
    if is_excluded(path):
        return False
    html = path.read_text(encoding="utf-8")
    if "<head" not in html.lower() or "</head>" not in html.lower():
        return False
    url_path = rel_url(path)
    if is_noindex(html, url_path):
        return False
    canonical = SITE + url_path
    m = re.search(r"(<head[^>]*>)(.*?)(</head>)", html, re.I | re.S)
    if not m:
        return False
    head_open, head, head_close = m.groups()
    head = remove_generated_seo(head)
    head = upsert_og_url(head, canonical)
    canonical_block = f'\n    <!-- Canonical / SEO -->\n    <link rel="canonical" href="{canonical}">\n'
    # Put canonical after title when possible, otherwise near top.
    title_m = re.search(r"</title>", head, re.I)
    if title_m:
        head = head[:title_m.end()] + canonical_block + head[title_m.end():]
    else:
        head = canonical_block + head
    schema_block = "\n    <!-- Freedom Lab structured data (generated by scripts/apply-seo.py) -->\n    " + "\n    ".join(json_script(s) for s in schemas_for(path, html, canonical)) + "\n"
    head = re.sub(r"(\n\s*){3,}$", "\n\n", head)
    if GA_SNIPPET_MARKER in head:
        ga_pos = head.find("<!-- Google tag")
        if ga_pos != -1:
            head = head[:ga_pos] + schema_block + head[ga_pos:]
        else:
            head += schema_block
    else:
        head += schema_block
    new_html = html[:m.start()] + head_open + head + head_close + html[m.end():]
    new_html = re.sub(r"\n(?:[ \t]*\n){2,}([ \t]*<!-- Freedom Lab structured data)", r"\n\n\1", new_html)
    new_html = "\n".join(line.rstrip() for line in new_html.splitlines()) + "\n"
    if new_html != html:
        path.write_text(new_html, encoding="utf-8")
        return True
    return False


def sitemap_entries() -> list[tuple[str, str, str]]:
    entries = []
    for path in sorted(ROOT.rglob("*.html")):
        if is_excluded(path) or path.name in EXCLUDE_FILES:
            continue
        html = path.read_text(encoding="utf-8", errors="ignore")
        url_path = rel_url(path)
        if is_noindex(html, url_path):
            continue
        if not (path.name == "index.html" or path == ROOT / "index.html"):
            continue
        priority = HIGH_PRIORITY.get(url_path, "0.8" if url_path.startswith("/resources/") else "0.7")
        lastmod = datetime.fromtimestamp(path.stat().st_mtime, timezone.utc).date().isoformat()
        entries.append((SITE + url_path, lastmod, priority))
    return entries


def write_sitemap() -> bool:
    rows = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    entries = sitemap_entries()
    entries.sort(key=lambda e: (0 if e[0] == SITE + "/" else 1, e[0]))
    for loc, lastmod, priority in entries:
        rows.append("  <url>")
        rows.append(f"    <loc>{escape(loc)}</loc>")
        rows.append(f"    <lastmod>{lastmod}</lastmod>")
        rows.append(f"    <priority>{priority}</priority>")
        rows.append("  </url>")
    rows.append("</urlset>")
    content = "\n".join(rows) + "\n"
    path = ROOT / "sitemap.xml"
    old = path.read_text(encoding="utf-8") if path.exists() else ""
    if old != content:
        path.write_text(content, encoding="utf-8")
        return True
    return False


def main() -> None:
    changed = []
    for path in sorted(ROOT.rglob("*.html")):
        if process_html(path):
            changed.append(path.relative_to(ROOT).as_posix())
    if write_sitemap():
        changed.append("sitemap.xml")
    print(f"SEO apply complete: {len(changed)} files changed")
    for item in changed:
        print(f" - {item}")


if __name__ == "__main__":
    main()
